version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "9002:3000"
    volumes:
      - .:/app
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000